2019-01-13 00:43:34.545 [error] <0.378.0>@Elixir.BinbaseBackend.MainSupervisor:init:21 CRASH REPORT Process <0.378.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BinbaseBackend.MainSupervisor':init([]) line 21
2019-01-13 02:03:39.146 [error] <0.476.0>@lists:reverse:147 CRASH REPORT Process <0.476.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}) line 147
2019-01-13 02:03:39.147 [error] <0.473.0>@lists:reverse:147 Supervisor {<0.473.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.107>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.475.0>, {<<"client 127.0.0.1:44513 -> 127.0.0.1:5672">>,1}) at <0.476.0> exit with reason no function clause matching lists:reverse(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}) line 147 in context child_terminated
2019-01-13 02:03:39.147 [error] <0.473.0> Supervisor {<0.473.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.107>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.475.0>, {<<"client 127.0.0.1:44513 -> 127.0.0.1:5672">>,1}) at <0.476.0> exit with reason reached_max_restart_intensity in context shutdown
2019-01-13 20:55:42.002 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.BinbaseBackend.MainSupervisor',{shutdown,{failed_to_start_child,'Elixir.BinbaseBackend.Engine.Listener',{undef,[{'Elixir.AMQPqueue.Queue',declare,[#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.486.0>},pid => <0.495.0>},<<"binbase_backend.queue">>,[{durable,false}]],[]},{'Elixir.BinbaseBackend.Engine.Listener',init,1,[{file,"lib/binbase_backend/engine/listener.ex"},{line,59}]},{gen_server,init_it,...},...]}}}}},...} in application_master:init/4 line 138
2019-01-14 21:28:01.213 [error] <0.481.0>@lists:reverse:147 CRASH REPORT Process <0.481.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{data => <<"me msg">>,type => <<"event">>}) line 147
2019-01-16 02:54:34.498 [error] <0.3316.0>@Elixir.BinbaseBackend.Engine.Broadcaster:init:45 CRASH REPORT Process <0.3316.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Broadcaster':init/1 line 45
2019-01-16 02:54:34.498 [error] <0.3296.0>@Elixir.BinbaseBackend.Engine.Broadcaster:init:45 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Broadcaster' started with 'Elixir.BinbaseBackend.Engine.Broadcaster':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Broadcaster':init/1 line 45 in context start_error
2019-01-16 02:55:13.284 [error] <0.442.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-01-16 02:55:13.284 [error] <0.463.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55
2019-01-16 02:55:57.559 [error] <0.479.0>@Elixir.BinbaseBackendWeb.UserSocket:child_spec CRASH REPORT Process <0.479.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.BinbaseBackendWeb.UserSocket':child_spec([{endpoint,'Elixir.BinbaseBackendWeb.Endpoint'},{websocket,true},{longpoll,false}])
2019-01-16 02:55:57.560 [error] <0.441.0>@Elixir.BinbaseBackendWeb.UserSocket:child_spec Supervisor 'Elixir.BinbaseBackend.Supervisor' had child 'Elixir.BinbaseBackendWeb.Endpoint' started with 'Elixir.BinbaseBackendWeb.Endpoint':start_link([]) at undefined exit with reason call to undefined function 'Elixir.BinbaseBackendWeb.UserSocket':child_spec([{endpoint,'Elixir.BinbaseBackendWeb.Endpoint'},{websocket,true},{longpoll,false}]) in context start_error
2019-01-16 03:00:37.322 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:00:37.371 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 CRASH REPORT Process 'Elixir.BinbaseBackend.Engine.Broadcaster' with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:01:56.017 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:01:56.053 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 CRASH REPORT Process 'Elixir.BinbaseBackend.Engine.Broadcaster' with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:03:07.188 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:03:07.226 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 CRASH REPORT Process 'Elixir.BinbaseBackend.Engine.Broadcaster' with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:05:42.229 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 03:05:42.264 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 CRASH REPORT Process 'Elixir.BinbaseBackend.Engine.Broadcaster' with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 14:40:31.179 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 14:49:17.132 [error] <0.462.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, [{type,<<"event">>}]) line 51
2019-01-16 14:49:47.370 [error] <0.462.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-01-16 15:03:14.283 [error] <0.462.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-01-16 15:03:31.181 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-01-16 15:19:55.067 [error] <0.462.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-01-16 15:22:20.250 [error] <0.453.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-01-16 15:37:58.358 [error] <0.467.0> gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: nil\n  event: nil\n  payload: \"me msg\"\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 227
2019-01-16 15:38:39.245 [error] <0.462.0> gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"trade\"\n  event: \"events\"\n  payload: \"me msg\"\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 227
2019-01-16 15:40:11.079 [error] <0.462.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, <<"me msg">>, []) line 51
2019-03-09 17:19:27.030 [error] <0.423.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-09 20:17:35.865 [error] <0.423.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-09 20:17:35.865 [error] <0.443.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55
2019-03-09 20:28:40.592 [error] <0.423.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,unknown_host} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-09 20:53:12.692 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-09 20:53:12.739 [error] <0.293.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.521.0>,1,<0.522.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-l...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-09 20:53:13.144 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-09 20:53:13.153 [error] <0.293.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.521.0>,2,<0.525.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-l...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-09 21:15:59.703 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-09 21:15:59.714 [error] <0.293.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.562.0>,1,<0.563.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-l...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-09 21:16:31.198 [error] <0.608.0> CRASH REPORT Process <0.608.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-09 21:16:31.211 [error] <0.293.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.607.0>,1,<0.608.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-l...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-10 21:52:44.864 [error] <0.583.0> CRASH REPORT Process <0.583.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<..>>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-10 21:52:44.926 [error] <0.294.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.582.0>,1,<0.583.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cac...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-10 21:53:34.598 [error] <0.587.0> CRASH REPORT Process <0.587.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<..>>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-10 21:53:34.606 [error] <0.294.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.586.0>,1,<0.587.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cac...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-10 21:57:31.791 [error] <0.593.0> CRASH REPORT Process <0.593.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<..>>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-10 21:57:31.802 [error] <0.294.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.592.0>,1,<0.593.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cac...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-03-11 16:32:38.768 [error] <0.394.0> Supervisor {<0.394.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.393.0>, <<"client 172.24.0.4:37765 -> 172.24.0.3:5672">>) at undefined exit with reason noproc in context shutdown_error
2019-03-11 16:37:31.674 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 68,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-11 16:37:31.731 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.562.0>,2,<0.565.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 68,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"application/json, text/plain, */*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,...">>,...},...}},...},...},...},...},...]},...}}
2019-03-11 16:43:30.257 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new_mail,message => nil,module => 'Elixir.Bamboo.Email',reason => nil},[{'Elixir.Bamboo.Email',new_mail,[[{to,<<"xarur@easyemail.info">>},{from,<<"ricking06@gmail.com">>},{subject,<<"Welcome!!!">>},{html_body,<<"<strong>WELCOME</strong>">>},{text_body,<<"WELCOME">>}]],[]},{'Elixir.BinbaseBackend.Accounts.Users',create_user,1,[{file,"lib/binbase_backend/accounts/users.ex"},{line,24}]},{'Elixir.BinbaseBackendWeb.UserController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-11 16:43:30.267 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.571.0>,2,<0.574.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new_mail,message => nil,module => 'Elixir.Bamboo.Email',reason => nil},[{'Elixir.Bamboo.Email',new_mail,[[{to,<<"xarur@easyemail.info">>},{from,<<"ricking06@gmail.com">>},{subject,<<"Welcome!!!">>},{html_body,<<"<strong>WELCOME</strong>">>},{text_body,<<"WELCOME">>}]],[]},{'Elixir.BinbaseBackend.Accounts.Users',...},...]},...},...]},...}}
2019-03-13 17:14:29.687 [error] <0.433.0> Supervisor {<0.433.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.432.0>, <<"client 172.24.0.4:52653 -> 172.24.0.3:5672">>) at undefined exit with reason noproc in context shutdown_error
2019-03-24 18:43:51.018 [error] <0.473.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-24 18:43:51.018 [error] <0.493.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 CRASH REPORT Process <0.493.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55
2019-03-24 21:07:42.379 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-24 21:29:23.882 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-25 18:19:49.479 [error] <0.516.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-25 18:47:59.038 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"G_ENABLED_I...">>,...},...}},...},...],...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-25 18:47:59.088 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.576.0>,1,<0.577.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"...">>,...},...}},...},...],...},...},...},...]},...}}
2019-03-25 18:47:59.577 [error] <0.607.0> CRASH REPORT Process <0.607.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"G_ENABLED_IDPS=google">>,<<"host">> => <<"localhost:4000">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-25 18:47:59.586 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.576.0>,2,<0.607.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-a...">>,...},...}},...},...},...},...},...]},...}}
2019-03-25 18:48:47.117 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...],...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-25 18:48:47.130 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.610.0>,1,<0.611.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"...">>,...},...}},...},...],...},...},...},...]},...}}
2019-03-25 18:50:07.773 [error] <0.627.0> CRASH REPORT Process <0.627.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...],...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2019-03-25 18:50:07.787 [error] <0.314.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.BinbaseBackendWeb.Endpoint.HTTP',<0.626.0>,1,<0.627.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"...">>,...},...}},...},...],...},...},...},...]},...}}
2019-03-25 21:46:29.025 [error] <0.485.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55
2019-03-25 21:46:29.025 [error] <0.465.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-25 21:46:29.032 [error] <0.464.0> Supervisor 'Elixir.BinbaseBackend.Supervisor' had child 'Elixir.BinbaseBackend.MainSupervisor' started with 'Elixir.BinbaseBackend.MainSupervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.BinbaseBackend.Engine.Listener',{{badmatch,{error,econnrefused}},[{'Elixir.BinbaseBackend.Engine.Listener',init,1,[{file,"lib/binbase_backend/engine/listener.ex"},{line,55}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}} in context start_error
2019-03-25 21:47:34.181 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-25 21:47:34.213 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 CRASH REPORT Process 'Elixir.BinbaseBackend.Engine.Broadcaster' with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 13:28:54.305 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 13:45:02.258 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 14:18:27.833 [error] <0.464.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,unknown_host} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-26 14:29:01.825 [error] <0.484.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 CRASH REPORT Process <0.484.0> with 0 neighbours crashed with reason: no match of right hand value {error,unknown_host} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55
2019-03-26 14:29:01.825 [error] <0.464.0>@Elixir.BinbaseBackend.Engine.Listener:init:55 Supervisor 'Elixir.BinbaseBackend.MainSupervisor' had child 'Elixir.BinbaseBackend.Engine.Listener' started with 'Elixir.BinbaseBackend.Engine.Listener':start_link() at undefined exit with reason no match of right hand value {error,unknown_host} in 'Elixir.BinbaseBackend.Engine.Listener':init/1 line 55 in context start_error
2019-03-26 14:36:54.998 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 15:00:44.585 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 15:19:25.202 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
2019-03-26 15:21:26.259 [error] <0.483.0>@Elixir.AMQP.Basic:publish:51 gen_server 'Elixir.BinbaseBackend.Engine.Broadcaster' terminated with reason: no function clause matching 'Elixir.AMQP.Basic':publish(ok, <<"binbase_backend.exchange">>, <<"binbase_backend.routing">>, #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, []) line 51
